---
- hosts: dev
  gather_facts: false
  tasks:
    - name: copy jar file to tomcat
      copy:
        src: /var/lib/jenkins/workspace/job1/target/spring-petclinic-2.4.5.jar
        dest: /opt/apache-tomcat-9.0.46/webapps