---
- hosts: dev
  tasks:
    - name: Stop Current running container
      command: docker stop devops-container
      ignore_errors: yes

    - name: Remove Stopped container
      command: docker rm devops-container
      ignore_errors: yes

    - name: Remove Docker Image
      command: docker rmi sdangat11/devops-image:latest
      ignore_errors: yes

    - name: pull docker image from Dockerhub
      command: docker pull sdangat11/devops-image:latest

    - name: Create container using devops-image
      command: docker run -d --name devops-container -p 8080:8080 sdangat11/devops-image:latest